package classes;
import java.util.Date;
public class Event implements Comparable<Event>{
    private Date date;
    private Timeslot startTime;
    private Location location;
    private Contact contact; // include department and email
    private int duration; // in minutes

    // Constructors
    public Event(Date date, Timeslot startTime, Location location, Contact contact, int duration) {
        this.date = date;
        this.startTime = startTime;
        this.location = location;
        this.contact = contact;
        this.duration = duration;
    }

    // Constants for time format
    private static final String timeFormat = "h:mma";
    private static final String dateFormat = "mm/dd/yyyy";

    // Methods
    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null || getClass() != obj.getClass()) return false;

        Event event = (Event) obj;

        if (!date.equals(event.date)) return false;
        if (!startTime.equals(event.startTime)) return false;
        return location.equals(event.location);
    }

    // Hashcode method (auto-generated by IDE)
    @Override
    public int hashCode() {
        int result = date.hashCode();
        result = 31 * result + startTime.hashCode();
        result = 31 * result + location.hashCode();
        return result;
    }

    // CompareTo method
    @Override
    public int compareTo(Event other) {
        int dateComparison = date.compareTo(other.date);
        if (dateComparison != 0) {
            return dateComparison;
        }
        return startTime.compareTo(other.startTime);
    }

    // ToString method
    @Override
    public String toString() {
        return "[Event Date: " + dateFormat.format(String.valueOf(date)) + "] [Start: " +
                timeFormat.format(String.valueOf(startTime)) + "] [End: " +
                timeFormat.format(new Timeslot(startTime.getTime() + duration * 60000)) + "] @" +
                location.toString() + " [Contact: " + contact.getDepartmentName() + ", " + contact.getEmail() + "]";
    }
}
